name: HelloWorld
description: ''
version: 1.1.1
author: null
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: helloworld
  parentArtefactID: bobwprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-02-14 15:50:57'
pipelines:
  pipelines/customers_orders:
    name: customers_orders
    description: Aggregates total spending's for each customer
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-02-14 15:50:58'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customers_orders
    subgraphs: []
    dependencies: {}
  pipelines/report_top_customers:
    name: report_top_customers
    description: Prepare a report based on customers' spending
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-02-14 15:50:58'
    datasets:
      inputs:
      - datasets/customers_orders
      outputs:
      - datasets/report
    subgraphs: []
    dependencies: {}
  pipelines/join_agg_sort:
    name: join_agg_sort
    description: Show an example of joining two datasets (customers and orders), aggregating
      (sales by customer), sorting (by totals)
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-02-14 15:50:58'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customer_totals
    subgraphs: []
    dependencies: {}
  pipelines/farmers-markets-irs:
    name: farmers-markets-irs
    description: Exploration of Farmer's Market Locations By US Zip Code
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-02-14 15:50:58'
    datasets:
      inputs:
      - datasets/farmers-markets
      - datasets/irs-zipcode-data
      outputs:
      - datasets/farmers_market_tax_report
    subgraphs: []
    dependencies: {}
  pipelines/DBX2Snow:
    name: DBX2Snow
    description: This codebase provides a pipeline for analyzing customer revenue
      and order data. It reads in customer and order data from CSV files, joins them
      based on customer_id, and calculates revenue and order count for each customer.
      The resulting data is then sorted by revenue in descending order and limited
      to the top 50 customers. Finally, the top 50 customers are written to a Snowflake
      table for further analysis and reporting.
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-15 14:25:09'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/table_snow
    subgraphs: []
    dependencies: {}
  pipelines/a1_FilterCriteria:
    name: a1_FilterCriteria
    description: ''
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-29 13:27:20'
    datasets:
      inputs:
      - datasets/customers
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/a2_DirectFieldMap:
    name: a2_DirectFieldMap
    description: ''
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-29 13:31:45'
    datasets:
      inputs:
      - datasets/customers
      outputs:
      - datasets/rbc_cust_target
    subgraphs: []
    dependencies: {}
  pipelines/a3_self_join:
    name: a3_self_join
    description: ''
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-04-05 15:08:03'
    datasets:
      inputs:
      - datasets/emp_stooges
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/report:
    name: report
    description: Final report for the bank
    author: bobw@prophecy.io
    createdAt: '2024-02-14 15:50:57'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 15:50:57'
  datasets/customer_totals:
    name: customer_totals
    description: Customers by total of their purchases
    author: bobw@prophecy.io
    createdAt: '2024-02-14 15:50:57'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 15:50:57'
  datasets/orders:
    name: orders
    description: All the orders placed by the customers
    author: bobw@prophecy.io
    createdAt: '2024-02-14 15:50:58'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 15:50:58'
  datasets/customers:
    name: customers
    description: All the customers
    author: bobw@prophecy.io
    createdAt: '2024-02-14 15:50:58'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 15:50:58'
  datasets/customers_orders:
    name: customers_orders
    description: Customers by total of their purchases
    author: bobw@prophecy.io
    createdAt: '2024-02-14 15:50:58'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 15:50:58'
  datasets/old_events:
    name: old_events
    description: Old events data
    author: bobw@prophecy.io
    createdAt: '2024-02-14 15:50:58'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 15:50:58'
  datasets/historic_events_flat:
    name: historic_events_flat
    description: Historic events flat
    author: bobw@prophecy.io
    createdAt: '2024-02-14 15:50:58'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 15:50:58'
  datasets/farmers-markets:
    name: farmers-markets
    description: Farmer's Market data
    author: bobw@prophecy.io
    createdAt: '2024-02-14 15:50:58'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 15:50:58'
  datasets/irs-zipcode-data:
    name: irs-zipcode-data
    description: Irs zipcode data
    author: bobw@prophecy.io
    createdAt: '2024-02-14 15:50:58'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 15:50:58'
  datasets/farmers_market_tax_report:
    name: farmers_market_tax_report
    description: Farmer's market tax report
    author: bobw@prophecy.io
    createdAt: '2024-02-14 15:50:58'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 15:50:58'
  datasets/table_snow:
    name: table_snow
    description: Output to Snowflake table
    author: bobw@prophecy.io
    createdAt: '2024-03-15 14:36:03'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Warehouse
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-15 14:36:03'
  datasets/rbc_cust_target:
    name: rbc_cust_target
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-29 13:40:01'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Warehouse
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-29 13:40:01'
  datasets/simple_map:
    name: simple_map
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-29 14:25:59'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-29 14:25:59'
  datasets/emp_stooges:
    name: emp_stooges
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-04-05 15:29:50'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-04-05 15:29:50'
templates: {}
jobs:
  jobs/run_1:
    name: run_1
    description: ''
    fabricUID: 9631
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 ? * 1 *
    timeout: null
    alerting:
      emails: bobw@prophecy.io
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/customers_orders
    - pipelines/report_top_customers
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2024-03-05 16:24:03'
    author: bobw@prophecy.io
  jobs/run_2_Airflow:
    name: run_2_Airflow
    description: Airflow
    fabricUID: 9770
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 * * 1
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-03-05 16:31:39'
    author: bobw@prophecy.io
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-02-14 15:50:57'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-04-05T15:07:10.011714Z'
  name: plibMaven
  version: 7.1.83
  id: '541171390'
  createdAt: '2024-04-05T15:07:10.011626Z'
- type: plibPypi
  modifiedAt: '2024-04-05T15:07:10.011783Z'
  name: plibPypi
  version: 1.8.13
  id: '2123059912'
  createdAt: '2024-04-05T15:07:10.011764Z'
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.4
    isDefault: true
    author: null
    createdAt: '2024-04-05 15:26:54'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.5
    isDefault: true
    author: null
    createdAt: '2024-04-05 15:26:52'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
